version: "3.9"

services:
  db:
    image: postgres:15
    container_name: farmfocus_db
    restart: always
    environment:
      POSTGRES_USER: farmfocus
      POSTGRES_PASSWORD: farmfocus
      POSTGRES_DB: farmfocus
    ports:
      - "10.155.36.40:5432:5432"  # Доступ к БД с внешнего IP
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - farmfocus-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: farmfocus_api
    restart: always
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports:
      - "10.155.36.40:8080:8080"  # API доступно с внешнего IP
    networks:
      - farmfocus-network

  migrate:
    image: golang:1.25-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    command: go run ./cmd/migrate/migrate.go
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - farmfocus-network

  bot-api:
    build:
      context: ./bot-api
      dockerfile: Dockerfile
    container_name: farmfocus_bot_api
    restart: always
    env_file:
      - ./bot-api/.env
    depends_on:
      - api
    networks:
      - farmfocus-network
    ports:
      - "10.155.36.40:8081:8080"  # Bot API доступно с внешнего IP

volumes:
  db_data:

networks:
  farmfocus-network:
    driver: bridge